name: ci-pipeline
run-name: ${{ github.actor }} is pushing code
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ubuntu
      run: sudo apt install make
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: make install
    - name: Run tests
      run: make test

